version: '3.9'

services:
  common:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    network_mode: host

  web:
    extends:
      service: common
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
