# Generated by Django 5.0.6 on 2024-05-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_place_alter_product_description_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="value",
        ),
    ]
