# Generated by Django 5.0.6 on 2024-05-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="full_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
