# Generated by Django 5.0.6 on 2024-05-23 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_order_email_alter_order_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(default=" ", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="full_name",
            field=models.CharField(default=" ", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
            preserve_default=False,
        ),
    ]
